/data/data/com.termux/files/home/donwloadss/cookie.txt                                                                       323/323               100%
# Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

faucetmegas.online      FALSE   /       FALSE   1717269690      csrf_cookie_name        dd4c12c8ff2c30404f242fd4e8ac9235
#HttpOnly_faucetmegas.online    FALSE   /       FALSE   1717269406      ci_session      di7gue068c7phsj87utntbmvqf4su719